/**
 * Global test setup, registered via `setupFilesAfterEnv` so that `jest.mock`,
 * `expect` and `beforeEach` are all available in one place. It still runs
 * before any test file's own imports are evaluated, so module mocks and
 * process.env writes here are early enough.
 *
 * jest-expo's own setup (`jest-expo/src/preset/setup.js`) has already run at
 * this point; it mocks every Expo native module, LogBox and the asset registry.
 */
import { configure } from '@testing-library/react-native';

// ---------------------------------------------------------------------------
// Environment
// ---------------------------------------------------------------------------
// babel-preset-expo rewrites `process.env.EXPO_PUBLIC_*` to `env.EXPO_PUBLIC_*`
// imported from `expo/virtual/env`, which is literally `export const env =
// process.env`. That is a live reference, so assigning here (before
// src/api/axios.ts is first required) is enough. Note this only holds outside a
// production build, where the value would instead be inlined at transform time.
process.env.EXPO_PUBLIC_API_URL = 'http://localhost:3000';

// ---------------------------------------------------------------------------
// Native module mocks
// ---------------------------------------------------------------------------

// Must be registered before the Reanimated mock, which imports Reanimated's
// real index and therefore pulls in worklets. Under `jest-expo/ios` the
// `native.*` moduleFileExtensions make `NativeWorklets.native.ts` win over the
// plain `.js` stub, and its module-scope `loadUnpackers()` throws on the absent
// TurboModule. The shipped mock provides the whole WorkletAPI surface
// (scheduleOnRN, runOnUI, ...) plus the _WORKLET / __RUNTIME_KIND globals.
jest.mock('react-native-worklets', () =>
  require('react-native-worklets/src/mock'),
);

// Reanimated 4. This is what `expo-router/testing-library` does internally, so
// it is Expo's own pattern for SDK 57. `setUpTests()` is the other mode: it
// keeps real Reanimated and adds `toHaveAnimatedStyle` plus a frame clock. Only
// reach for that when actually asserting on animated styles.
jest.mock('react-native-reanimated', () =>
  require('react-native-reanimated/mock'),
);

// This file is itself a bundle of jest.mock() calls, so it is required for its
// side effects rather than passed to jest.mock().
require('react-native-gesture-handler/jestSetup');

// Ships a complete jest mock module: KeyboardStickyView -> View,
// KeyboardAwareScrollView -> ScrollView, KeyboardController -> jest.fn()s.
jest.mock('react-native-keyboard-controller', () =>
  require('react-native-keyboard-controller/jest'),
);

// Official mock: SafeAreaProvider becomes a pure context provider that honours
// `initialMetrics`, and useSafeAreaInsets falls back to zero insets with no
// provider present.
jest.mock(
  'react-native-safe-area-context',
  () => require('react-native-safe-area-context/jest/mock').default,
);

// expo-crypto's autogenerated mock declares `randomUUID(): any {}` - it returns
// undefined. useCreatePost keys its optimistic update on that value, and
// `post.tempId === undefined` would then match every non-optimistic post.
// The `mock` prefix is required: jest hoists the factory above this
// declaration, and only mock-prefixed names are allowed to be referenced.
let mockUuidCounter = 0;
jest.mock('expo-crypto', () => ({
  ...jest.requireActual('expo-crypto'),
  randomUUID: jest.fn(() => `test-uuid-${++mockUuidCounter}`),
}));

// Reset per test so the first UUID in any test is always `test-uuid-1`.
beforeEach(() => {
  mockUuidCounter = 0;
});

// ---------------------------------------------------------------------------
// React Native Testing Library
// ---------------------------------------------------------------------------
// RNTL 14 auto-registers its matchers and an afterEach cleanup on import.
// `concurrentRoot` is gone in v14 - it was a react-test-renderer concern, and
// v14 renders through `test-renderer`.
configure({
  asyncUtilTimeout: 5000,
});
